# Generated by Django 3.1.1 on 2020-09-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(default='polls/static/acebackup/', max_length=200)),
                ('log', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlcatelUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_01', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_01', models.IntegerField(default=0)),
                ('name_02', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_02', models.IntegerField(default=0)),
                ('name_03', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_03', models.IntegerField(default=0)),
                ('name_04', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_04', models.IntegerField(default=0)),
                ('name_05', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_05', models.IntegerField(default=0)),
                ('name_06', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_06', models.IntegerField(default=0)),
                ('name_07', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_07', models.IntegerField(default=0)),
                ('name_08', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_08', models.IntegerField(default=0)),
                ('name_09', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_09', models.IntegerField(default=0)),
                ('name_10', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('counter_10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontakt', models.CharField(max_length=20)),
                ('proizvodjac', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('log', models.TextField()),
                ('winlock', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('winlockversion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('createdby', models.CharField(max_length=100)),
                ('createdbygroup', models.CharField(max_length=100)),
                ('datecreated', models.DateTimeField()),
                ('datesent', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontakt', models.CharField(max_length=20)),
                ('proizvodjac', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('log', models.TextField()),
                ('winlock', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('winlockversion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('createdby', models.CharField(max_length=100)),
                ('createdbygroup', models.CharField(max_length=100)),
                ('datecreated', models.DateTimeField()),
                ('datesent', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontakt', models.CharField(max_length=20)),
                ('proizvodjac', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('log', models.TextField()),
                ('winlock', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('winlockversion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('createdby', models.CharField(max_length=100)),
                ('createdbygroup', models.CharField(max_length=100)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HtcUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HuaweiUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LgUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LumiaUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyTAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tac', models.CharField(max_length=8)),
                ('proizvodjac', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NokiaModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('modeltype', models.CharField(max_length=20)),
                ('typeid', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('fullwinlock', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('winlock', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('altversion', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NokiaUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SamsungUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=100)),
                ('usergroup', models.CharField(max_length=100)),
                ('lockstatus', models.CharField(max_length=1)),
                ('datenow', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonyUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnlockTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('proizvodjac', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='a.miljkovic@vipmobile.rs', max_length=200)),
                ('cc', models.CharField(default='a.miljkovic@vipmobile.rs', max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('mailbody', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ZteUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('unlock', models.CharField(max_length=50)),
            ],
        ),
    ]
