# Generated by Django 3.0.dev20190528134031 on 2020-09-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='createdbygroup',
        ),
        migrations.RemoveField(
            model_name='deletedtable',
            name='createdbygroup',
        ),
        migrations.RemoveField(
            model_name='entrytable',
            name='createdbygroup',
        ),
    ]
