# Generated by Django 3.0.dev20190528134031 on 2020-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200911_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='createdbygroup',
            field=models.CharField(default='level_1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedtable',
            name='createdbygroup',
            field=models.CharField(default='level_1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrytable',
            name='createdbygroup',
            field=models.CharField(default='level_1', max_length=100),
            preserve_default=False,
        ),
    ]
