# Generated by Django 3.0.dev20190528134031 on 2020-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200911_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytable',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrytable',
            name='unlock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrytable',
            name='winlock',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrytable',
            name='winlockversion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
