# Generated by Django 3.0.dev20190528134031 on 2020-09-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200912_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytable',
            name='model',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
