# Generated by Django 3.0.dev20190528134031 on 2020-09-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200912_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytable',
            name='unlock',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrytable',
            name='winlock',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrytable',
            name='winlockversion',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
